-- ============================================================
-- 밀알교회 Admin CMS - 샘플 데이터 (테이블당 ~100개)
-- 초기 로그인: superadmin / Admin@1234
-- ============================================================
USE milal_homepage;
SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

TRUNCATE TABLE texts;
TRUNCATE TABLE sections;
TRUNCATE TABLE pages;
TRUNCATE TABLE page_views;
TRUNCATE TABLE news;
TRUNCATE TABLE department_announcements;
TRUNCATE TABLE departments;
TRUNCATE TABLE together_items;
TRUNCATE TABLE bulletin_images;
TRUNCATE TABLE bulletins;
TRUNCATE TABLE sermons;
TRUNCATE TABLE announcements;
TRUNCATE TABLE hero_front_images;
TRUNCATE TABLE hero_background_images;
TRUNCATE TABLE heroes;
TRUNCATE TABLE members;
TRUNCATE TABLE users;
TRUNCATE TABLE role_permissions;
TRUNCATE TABLE permissions;
TRUNCATE TABLE roles;

-- ============================================================
-- ROLES
-- ============================================================
INSERT INTO `roles` (`id`,`name`,`slug`,`description`) VALUES
(1,'슈퍼 관리자','super-admin','모든 권한 보유'),
(2,'일반 관리자','manager','콘텐츠 관리 권한'),
(3,'뷰어','viewer','조회만 가능');

-- ============================================================
-- PERMISSIONS
-- ============================================================
INSERT INTO `permissions` (`name`,`slug`,`module`,`action`) VALUES
('히어로 조회','heroes.view','heroes','view'),('히어로 등록','heroes.create','heroes','create'),('히어로 수정','heroes.edit','heroes','edit'),('히어로 삭제','heroes.delete','heroes','delete'),
('교인 조회','members.view','members','view'),('교인 등록','members.create','members','create'),('교인 수정','members.edit','members','edit'),('교인 삭제','members.delete','members','delete'),
('공지 조회','announcements.view','announcements','view'),('공지 등록','announcements.create','announcements','create'),('공지 수정','announcements.edit','announcements','edit'),('공지 삭제','announcements.delete','announcements','delete'),
('뉴스 조회','news.view','news','view'),('뉴스 등록','news.create','news','create'),('뉴스 수정','news.edit','news','edit'),('뉴스 삭제','news.delete','news','delete'),
('설교 조회','sermons.view','sermons','view'),('설교 등록','sermons.create','sermons','create'),('설교 수정','sermons.edit','sermons','edit'),('설교 삭제','sermons.delete','sermons','delete'),
('주보 조회','bulletins.view','bulletins','view'),('주보 등록','bulletins.create','bulletins','create'),('주보 수정','bulletins.edit','bulletins','edit'),('주보 삭제','bulletins.delete','bulletins','delete'),
('부서 조회','departments.view','departments','view'),('부서 등록','departments.create','departments','create'),('부서 수정','departments.edit','departments','edit'),('부서 삭제','departments.delete','departments','delete'),
('CMS 조회','cms.view','cms','view'),('CMS 등록','cms.create','cms','create'),('CMS 수정','cms.edit','cms','edit'),('CMS 삭제','cms.delete','cms','delete'),
('사용자 조회','users.view','users','view'),('사용자 등록','users.create','users','create'),('사용자 수정','users.edit','users','edit'),('사용자 삭제','users.delete','users','delete');

INSERT INTO `role_permissions`(`role_id`,`permission_id`) SELECT 1,id FROM `permissions`;
INSERT INTO `role_permissions`(`role_id`,`permission_id`) SELECT 2,id FROM `permissions` WHERE `module`!='users';
INSERT INTO `role_permissions`(`role_id`,`permission_id`) SELECT 3,id FROM `permissions` WHERE `action`='view';

-- ============================================================
-- USERS 100개
-- 비밀번호 모두: Admin@1234
-- bcrypt hash (cost=10): $2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e
-- ============================================================
INSERT INTO `users` (`role_id`,`username`,`email`,`password_hash`,`name`,`full_name`,`is_active`) VALUES
(1,'superadmin','superadmin@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','관리자','슈퍼 관리자',1),
(2,'manager01','manager01@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','김관리','김관리자',1),
(2,'manager02','manager02@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','이관리','이관리자',1),
(2,'manager03','manager03@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','박관리','박관리자',1),
(2,'manager04','manager04@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','최관리','최관리자',1),
(2,'manager05','manager05@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','정관리','정관리자',0),
(3,'viewer01','viewer01@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','김뷰어','김뷰어',1),
(3,'viewer02','viewer02@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','이뷰어','이뷰어',1),
(3,'viewer03','viewer03@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','박뷰어','박뷰어',1),
(3,'viewer04','viewer04@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','최뷰어','최뷰어',1),
(2,'staff01','staff01@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','홍길동','홍길동',1),
(2,'staff02','staff02@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','임꺽정','임꺽정',1),
(2,'staff03','staff03@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','장보고','장보고',1),
(2,'staff04','staff04@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','이순신','이순신',1),
(2,'staff05','staff05@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','세종대왕','세종대왕',1),
(3,'staff06','staff06@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','강감찬','강감찬',1),
(3,'staff07','staff07@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','을지문덕','을지문덕',1),
(3,'staff08','staff08@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','광개토왕','광개토왕',0),
(3,'staff09','staff09@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','신사임당','신사임당',1),
(3,'staff10','staff10@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','유관순','유관순',1),
(2,'user21','user21@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','김민준','김민준',1),
(2,'user22','user22@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','이서준','이서준',1),
(2,'user23','user23@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','박도윤','박도윤',1),
(2,'user24','user24@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','최주원','최주원',1),
(2,'user25','user25@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','정시우','정시우',1),
(3,'user26','user26@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','강지호','강지호',1),
(3,'user27','user27@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','조준서','조준서',1),
(3,'user28','user28@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','윤서진','윤서진',1),
(3,'user29','user29@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','임하준','임하준',1),
(3,'user30','user30@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','오지유','오지유',1),
(2,'user31','user31@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','김서아','김서아',1),
(2,'user32','user32@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','이하은','이하은',1),
(2,'user33','user33@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','박수아','박수아',1),
(2,'user34','user34@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','최지아','최지아',0),
(2,'user35','user35@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','정나은','정나은',1),
(3,'user36','user36@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','강다은','강다은',1),
(3,'user37','user37@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','조아름','조아름',1),
(3,'user38','user38@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','윤채원','윤채원',1),
(3,'user39','user39@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','임소윤','임소윤',1),
(3,'user40','user40@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','오예린','오예린',1),
(2,'user41','user41@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','신유준','신유준',1),
(2,'user42','user42@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','권지훈','권지훈',1),
(2,'user43','user43@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','황건우','황건우',1),
(2,'user44','user44@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','안태양','안태양',1),
(2,'user45','user45@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','배준혁','배준혁',1),
(3,'user46','user46@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','노현우','노현우',1),
(3,'user47','user47@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','류승민','류승민',1),
(3,'user48','user48@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','문성준','문성준',1),
(3,'user49','user49@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','방태현','방태현',1),
(3,'user50','user50@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','서정우','서정우',1),
(2,'user51','user51@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','성민호','성민호',1),
(2,'user52','user52@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','손동현','손동현',1),
(2,'user53','user53@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','심재원','심재원',1),
(2,'user54','user54@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','양호준','양호준',0),
(2,'user55','user55@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','어준호','어준호',1),
(3,'user56','user56@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','엄태준','엄태준',1),
(3,'user57','user57@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','여준서','여준서',1),
(3,'user58','user58@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','오성민','오성민',1),
(3,'user59','user59@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','우지훈','우지훈',1),
(3,'user60','user60@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','유태양','유태양',1),
(2,'user61','user61@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','이건우','이건우',1),
(2,'user62','user62@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','임도현','임도현',1),
(2,'user63','user63@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','장수호','장수호',1),
(2,'user64','user64@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','전민준','전민준',0),
(2,'user65','user65@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','정재현','정재현',1),
(3,'user66','user66@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','조현우','조현우',1),
(3,'user67','user67@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','주성민','주성민',1),
(3,'user68','user68@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','지준혁','지준혁',1),
(3,'user69','user69@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','차태현','차태현',1),
(3,'user70','user70@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','채민호','채민호',1),
(2,'user71','user71@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','최건호','최건호',1),
(2,'user72','user72@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','추준서','추준서',1),
(2,'user73','user73@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','탁성호','탁성호',1),
(2,'user74','user74@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','편준혁','편준혁',1),
(2,'user75','user75@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','하태준','하태준',1),
(3,'user76','user76@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','한민준','한민준',1),
(3,'user77','user77@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','허준호','허준호',1),
(3,'user78','user78@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','홍승민','홍승민',1),
(3,'user79','user79@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','황재원','황재원',1),
(3,'user80','user80@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','길동무','길동무',1),
(2,'user81','user81@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','남궁민','남궁민',1),
(2,'user82','user82@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','독고준','독고준',1),
(2,'user83','user83@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','사공호','사공호',1),
(2,'user84','user84@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','선우진','선우진',1),
(2,'user85','user85@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','어우준','어우준',1),
(3,'user86','user86@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','황보민','황보민',1),
(3,'user87','user87@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','제갈현','제갈현',1),
(3,'user88','user88@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','복거준','복거준',1),
(3,'user89','user89@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','빈승우','빈승우',1),
(3,'user90','user90@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','석민준','석민준',1),
(2,'user91','user91@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','설준혁','설준혁',1),
(2,'user92','user92@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','소민호','소민호',1),
(2,'user93','user93@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','송태준','송태준',1),
(2,'user94','user94@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','순현우','순현우',1),
(2,'user95','user95@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','승준서','승준서',1),
(3,'user96','user96@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','시민준','시민준',1),
(3,'user97','user97@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','아준호','아준호',1),
(3,'user98','user98@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','야태현','야태현',1),
(3,'user99','user99@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','여민호','여민호',1),
(3,'user100','user100@milal.org','$2y$10$wMSbpxFVNq8J5yVUJoMfCOh7hbxKpE0kj8v6.bSv6qVrFCNqvNS9e','오태준','오태준',1);

-- ============================================================
-- MEMBERS 100개
-- ============================================================
INSERT INTO `members` (`name`,`title`,`role`,`position`,`biography`,`sort_order`,`is_active`) VALUES
('홍길동','담임목사','담임','목사','밀알교회 담임목사로 20년째 섬기고 있습니다.',1,1),
('김철수','부목사','교육','목사','청년부와 교육부를 담당합니다.',2,1),
('이영희','전도사','유아부','전도사','유아부 어린이들을 사랑으로 돌봅니다.',3,1),
('박민수','전도사','청년','전도사','청년부 예배를 담당합니다.',4,1),
('최지현','장로','원로','장로','30년간 교회를 섬겨온 원로 장로입니다.',5,1),
('정수진','권사','여성부','권사','여성부 활동을 이끌고 있습니다.',6,1),
('강동원','집사','미디어','집사','예배 영상과 음향을 담당합니다.',7,1),
('조민아','집사','찬양','집사','찬양팀 리더로 섬기고 있습니다.',8,1),
('윤서준','안수집사','봉사','안수집사','교회 봉사 전반을 조율합니다.',9,1),
('임하늘','전도사','중등부','전도사','중등부 청소년들을 지도합니다.',10,1),
('오지훈','목사','협동','목사','협동목사로 사역을 돕습니다.',11,1),
('신유리','전도사','고등부','전도사','고등부 예배와 수련회를 담당합니다.',12,1),
('권태양','집사','주차','집사','주차봉사팀을 이끕니다.',13,1),
('황보라','권사','심방','권사','심방 사역을 담당합니다.',14,1),
('안준혁','장로','재정','장로','교회 재정을 관리합니다.',15,1),
('배수아','전도사','유치부','전도사','유치부 어린이를 섬깁니다.',16,1),
('노현준','집사','예배','집사','예배 진행을 담당합니다.',17,1),
('류지은','권사','새신자','권사','새신자 양육을 맡고 있습니다.',18,1),
('문성호','안수집사','시설','안수집사','교회 시설 관리를 담당합니다.',19,1),
('방태현','전도사','소년부','전도사','소년부 어린이들과 함께합니다.',20,1),
('서정민','집사','찬양','집사','찬양대 반주를 맡고 있습니다.',21,1),
('성민아','권사','전도','권사','전도 사역을 담당합니다.',22,1),
('손준서','집사','방송','집사','방송 시스템을 운영합니다.',23,1),
('심재영','장로','교육','장로','교육부 운영을 지원합니다.',24,1),
('양호철','안수집사','식당','안수집사','교회 식당 봉사를 이끕니다.',25,1),
('어준호','집사','안내','집사','예배 안내 봉사를 담당합니다.',26,1),
('엄태양','권사','경배찬양','권사','경배찬양팀을 섬깁니다.',27,1),
('여승민','전도사','영아부','전도사','영아부 사역을 담당합니다.',28,1),
('오성준','집사','청년2부','집사','청년2부 활동을 지원합니다.',29,1),
('우지현','권사','선교','권사','해외선교팀을 담당합니다.',30,1),
('유태준','장로','감사','장로','감사위원으로 섬깁니다.',31,1),
('이건우','전도사','초등부','전도사','초등부 예배를 인도합니다.',32,1),
('임도현','집사','기도','집사','중보기도팀을 이끕니다.',33,1),
('장수민','권사','여전도','권사','여전도회를 이끌고 있습니다.',34,1),
('전민준','안수집사','환경','안수집사','교회 환경 정비를 담당합니다.',35,1),
('정재현','집사','남전도','집사','남전도회 활동을 지원합니다.',36,1),
('조현우','전도사','장년부','전도사','장년부 소그룹을 담당합니다.',37,1),
('주성민','권사','구역','권사','구역 모임을 조율합니다.',38,1),
('지준혁','집사','의료','집사','의료봉사팀을 운영합니다.',39,1),
('차태민','장로','호남','장로','지방 성도들을 섬깁니다.',40,1),
('채민호','전도사','어린이','전도사','어린이 예배를 진행합니다.',41,1),
('최건호','집사','법률','집사','법률 자문을 담당합니다.',42,1),
('추준서','안수집사','회계','안수집사','회계 업무를 보조합니다.',43,1),
('탁성준','집사','IT','집사','교회 IT 인프라를 담당합니다.',44,1),
('편준혁','권사','어르신','권사','어르신 사역을 담당합니다.',45,1),
('하태준','전도사','사역훈련','전도사','사역자 훈련을 담당합니다.',46,1),
('한민준','집사','다음세대','집사','다음세대 사역을 지원합니다.',47,1),
('허준호','장로','교구','장로','1교구를 담당합니다.',48,1),
('홍승민','집사','격려','집사','격려 사역을 담당합니다.',49,1),
('황재원','권사','도서','권사','교회 도서실을 운영합니다.',50,1),
('강지민','전도사','특수','전도사','장애인 사역을 담당합니다.',51,1),
('고민준','집사','교통','집사','교통 봉사를 이끕니다.',52,1),
('곽태현','안수집사','외국인','안수집사','외국인 사역을 담당합니다.',53,1),
('구성호','권사','독거','권사','독거노인 봉사를 합니다.',54,1),
('기준혁','집사','청소','집사','교회 청소 봉사를 합니다.',55,1),
('나현우','전도사','군선교','전도사','군 선교를 담당합니다.',56,1),
('남태양','장로','원로2','장로','원로 장로로 섬깁니다.',57,1),
('노승민','집사','카페','집사','교회 카페를 운영합니다.',58,1),
('단민호','권사','상담','권사','상담 사역을 담당합니다.',59,1),
('도준서','안수집사','교도소','안수집사','교도소 선교를 합니다.',60,1),
('동재현','전도사','문화','전도사','문화 사역을 담당합니다.',61,1),
('두현우','집사','성경공부','집사','성경공부 모임을 이끕니다.',62,1),
('등태준','권사','결혼','권사','결혼예식을 담당합니다.',63,1),
('란민준','장로','2교구','장로','2교구를 담당합니다.',64,1),
('마준혁','전도사','사춘기','전도사','중고등 사역을 담당합니다.',65,1),
('매성민','집사','농어촌','집사','농어촌 선교를 합니다.',66,1),
('맹태현','안수집사','도시','안수집사','도시 선교를 담당합니다.',67,1),
('모현우','권사','기도원','권사','기도원 사역을 담당합니다.',68,1),
('묘민호','집사','독서','집사','독서 모임을 이끕니다.',69,1),
('무준서','전도사','스포츠','전도사','스포츠 선교를 담당합니다.',70,1),
('미재현','장로','3교구','장로','3교구를 담당합니다.',71,1),
('민준혁','집사','봉사2','집사','봉사팀 2조를 이끕니다.',72,1),
('발성호','권사','탁아소','권사','탁아소 운영을 돕습니다.',73,1),
('방현우','안수집사','중보','안수집사','중보기도를 담당합니다.',74,1),
('배태양','전도사','캠퍼스','전도사','캠퍼스 선교를 담당합니다.',75,1),
('백준서','집사','새벽','집사','새벽예배 봉사를 합니다.',76,1),
('범재현','권사','오후','권사','오후예배를 담당합니다.',77,1),
('변민준','장로','4교구','장로','4교구를 담당합니다.',78,1),
('보준혁','전도사','인터넷','전도사','온라인 사역을 담당합니다.',79,1),
('복성민','집사','유튜브','집사','유튜브 채널을 운영합니다.',80,1),
('봉태현','안수집사','SNS','안수집사','SNS 사역을 담당합니다.',81,1),
('부현우','권사','통역','권사','통역 봉사를 합니다.',82,1),
('비민호','집사','글쓰기','집사','교회 소식지를 작성합니다.',83,1),
('빈준서','전도사','그림','전도사','예술 사역을 담당합니다.',84,1),
('사민준','집사','드라마','집사','드라마 사역을 합니다.',85,1),
('산준혁','권사','음악','권사','음악 사역을 담당합니다.',86,1),
('삼현우','전도사','오케스트라','전도사','오케스트라를 담당합니다.',87,1),
('상태양','집사','밴드','집사','워십밴드를 담당합니다.',88,1),
('새준서','권사','무용','권사','무용팀을 이끕니다.',89,1),
('생민준','전도사','인형극','전도사','인형극 사역을 합니다.',90,1),
('서준혁','집사','마임','집사','마임 사역을 담당합니다.',91,1),
('석성민','권사','서예','권사','서예 사역을 합니다.',92,1),
('선태현','안수집사','사진','안수집사','사진 기록을 담당합니다.',93,1),
('설현우','집사','영상','집사','영상 제작을 담당합니다.',94,1),
('소민호','전도사','팟캐스트','전도사','팟캐스트를 운영합니다.',95,1),
('속준서','장로','5교구','장로','5교구를 담당합니다.',96,1),
('손재현','집사','글로벌','집사','글로벌 사역을 지원합니다.',97,1),
('송태준','목사','은퇴','목사','은퇴 목사로 자문을 맡고 있습니다.',98,1),
('신현우','집사','재무','집사','재무 행정을 돕습니다.',99,1),
('심준서','권사','나눔','권사','나눔 사역을 담당합니다.',100,1);

-- ============================================================
-- HEROES 100개
-- ============================================================
INSERT INTO `heroes` (`title`,`image_path`,`main_title_ko`,`main_title_en`,`sub_title_ko`,`sub_title_en`,`sort_order`,`is_active`) VALUES
('히어로 1','heroes/hero_01.jpg','함께하는 교회','Church Together','모든 이를 환영합니다','Everyone is Welcome',1,1),
('히어로 2','heroes/hero_02.jpg','말씀과 함께','With the Word','성경 중심 교회','Bible-Centered Church',2,1),
('히어로 3','heroes/hero_03.jpg','찬양의 교회','Church of Praise','하나님께 영광','Glory to God',3,1),
('히어로 4','heroes/hero_04.jpg','기도하는 교회','Praying Church','중보기도 사역','Intercessory Prayer',4,1),
('히어로 5','heroes/hero_05.jpg','선교하는 교회','Missionary Church','땅 끝까지 복음을','Gospel to the Ends',5,1),
('히어로 6','heroes/hero_06.jpg','섬기는 교회','Serving Church','이웃 사랑 실천','Practicing Neighbor Love',6,1),
('히어로 7','heroes/hero_07.jpg','교육하는 교회','Educational Church','다음 세대를 세운다','Building Next Generation',7,1),
('히어로 8','heroes/hero_08.jpg','교제하는 교회','Fellowship Church','한 몸 된 공동체','One Body Community',8,1),
('히어로 9','heroes/hero_09.jpg','청년의 교회','Youth Church','청년이 살아있는','A Church Alive with Youth',9,1),
('히어로 10','heroes/hero_10.jpg','어린이의 교회','Children Church','어린이가 행복한','Where Children are Happy',10,1),
('히어로 11','heroes/hero_11.jpg','하나님의 사랑','God is Love','사랑의 교회','Church of Love',11,1),
('히어로 12','heroes/hero_12.jpg','은혜의 교회','Church of Grace','은혜가 넘치는','Overflowing with Grace',12,1),
('히어로 13','heroes/hero_13.jpg','평화의 교회','Church of Peace','평화를 나누는','Sharing Peace',13,1),
('히어로 14','heroes/hero_14.jpg','소망의 교회','Church of Hope','희망을 전하는','Conveying Hope',14,1),
('히어로 15','heroes/hero_15.jpg','믿음의 교회','Church of Faith','믿음으로 서는','Standing in Faith',15,1),
('히어로 16','heroes/hero_16.jpg','생명의 교회','Church of Life','생명을 살리는','Saving Lives',16,1),
('히어로 17','heroes/hero_17.jpg','빛의 교회','Church of Light','세상의 빛이 되는','Light of the World',17,0),
('히어로 18','heroes/hero_18.jpg','소금의 교회','Salt of Earth','세상의 소금','Salt of the World',18,1),
('히어로 19','heroes/hero_19.jpg','부활의 교회','Resurrection Church','부활을 믿는','Believing in Resurrection',19,1),
('히어로 20','heroes/hero_20.jpg','성령의 교회','Spirit-Filled Church','성령 충만한','Spirit-Filled',20,1),
('히어로 21','heroes/hero_21.jpg','치유의 교회','Healing Church','치유가 일어나는','Where Healing Happens',21,1),
('히어로 22','heroes/hero_22.jpg','예배의 교회','Worshiping Church','참된 예배','True Worship',22,1),
('히어로 23','heroes/hero_23.jpg','훈련의 교회','Training Church','제자를 세우는','Raising Disciples',23,1),
('히어로 24','heroes/hero_24.jpg','나눔의 교회','Sharing Church','나눔을 실천하는','Practicing Sharing',24,1),
('히어로 25','heroes/hero_25.jpg','회복의 교회','Restoring Church','상처를 회복하는','Restoring the Wounded',25,1),
('히어로 26','heroes/hero_26.jpg','연합의 교회','United Church','하나로 연합하는','United as One',26,1),
('히어로 27','heroes/hero_27.jpg','전도의 교회','Evangelizing Church','복음을 전하는','Proclaiming Gospel',27,1),
('히어로 28','heroes/hero_28.jpg','성장의 교회','Growing Church','날마다 성장하는','Growing Daily',28,0),
('히어로 29','heroes/hero_29.jpg','감사의 교회','Thankful Church','감사가 넘치는','Overflowing Gratitude',29,1),
('히어로 30','heroes/hero_30.jpg','헌신의 교회','Devoted Church','헌신으로 섬기는','Serving with Dedication',30,1),
('히어로 31','heroes/hero_31.jpg','화해의 교회','Reconciling Church','화해를 이루는','Achieving Reconciliation',31,1),
('히어로 32','heroes/hero_32.jpg','위로의 교회','Comforting Church','위로를 전하는','Conveying Comfort',32,1),
('히어로 33','heroes/hero_33.jpg','거룩의 교회','Holy Church','거룩함을 추구하는','Pursuing Holiness',33,1),
('히어로 34','heroes/hero_34.jpg','순종의 교회','Obedient Church','순종하는 삶','Life of Obedience',34,1),
('히어로 35','heroes/hero_35.jpg','전통의 교회','Traditional Church','전통을 이어가는','Continuing Tradition',35,1),
('히어로 36','heroes/hero_36.jpg','혁신의 교회','Innovative Church','새롭게 도전하는','Daring to Innovate',36,1),
('히어로 37','heroes/hero_37.jpg','창조의 교회','Creative Church','창의적으로 섬기는','Serving Creatively',37,1),
('히어로 38','heroes/hero_38.jpg','변화의 교회','Transforming Church','세상을 변화시키는','Transforming World',38,1),
('히어로 39','heroes/hero_39.jpg','소통의 교회','Communicating Church','소통으로 하나되는','United through Communication',39,1),
('히어로 40','heroes/hero_40.jpg','공동체 교회','Community Church','함께하는 공동체','Community Together',40,1),
('히어로 41','heroes/hero_41.jpg','가정의 교회','Family Church','가정을 세우는','Building Families',41,1),
('히어로 42','heroes/hero_42.jpg','노인의 교회','Senior Church','어르신을 섬기는','Serving Seniors',42,1),
('히어로 43','heroes/hero_43.jpg','장애인의 교회','Inclusive Church','모두를 품는','Embracing Everyone',43,1),
('히어로 44','heroes/hero_44.jpg','지역의 교회','Local Church','지역을 섬기는','Serving the Region',44,1),
('히어로 45','heroes/hero_45.jpg','세계의 교회','Global Church','세계를 품는','Embracing the World',45,1),
('히어로 46','heroes/hero_46.jpg','문화의 교회','Cultural Church','문화를 선도하는','Leading Culture',46,1),
('히어로 47','heroes/hero_47.jpg','예술의 교회','Artistic Church','예술로 예배하는','Worshiping through Art',47,1),
('히어로 48','heroes/hero_48.jpg','음악의 교회','Musical Church','음악으로 찬양하는','Praising through Music',48,0),
('히어로 49','heroes/hero_49.jpg','디지털 교회','Digital Church','디지털로 소통하는','Communicating Digitally',49,1),
('히어로 50','heroes/hero_50.jpg','미래의 교회','Future Church','미래를 향해 나아가는','Moving toward Future',50,1),
('히어로 51','heroes/hero_51.jpg','개혁의 교회','Reformed Church','늘 개혁하는','Always Reforming',51,1),
('히어로 52','heroes/hero_52.jpg','신뢰의 교회','Trustworthy Church','신뢰를 쌓는','Building Trust',52,1),
('히어로 53','heroes/hero_53.jpg','정직의 교회','Honest Church','정직하게 살아가는','Living Honestly',53,1),
('히어로 54','heroes/hero_54.jpg','겸손의 교회','Humble Church','겸손히 섬기는','Serving Humbly',54,1),
('히어로 55','heroes/hero_55.jpg','용서의 교회','Forgiving Church','용서를 실천하는','Practicing Forgiveness',55,1),
('히어로 56','heroes/hero_56.jpg','사랑실천 교회','Love in Action','사랑을 행동으로','Love in Action',56,1),
('히어로 57','heroes/hero_57.jpg','비전의 교회','Visionary Church','비전을 품은','Having Vision',57,1),
('히어로 58','heroes/hero_58.jpg','사명의 교회','Mission Church','사명을 다하는','Fulfilling Mission',58,1),
('히어로 59','heroes/hero_59.jpg','진리의 교회','Church of Truth','진리를 따르는','Following Truth',59,1),
('히어로 60','heroes/hero_60.jpg','생명력 교회','Vibrant Church','생명이 넘치는','Overflowing with Life',60,1),
('히어로 61','heroes/hero_61.jpg','능력의 교회','Powerful Church','능력으로 사역하는','Ministering with Power',61,1),
('히어로 62','heroes/hero_62.jpg','기적의 교회','Miracle Church','기적을 경험하는','Experiencing Miracles',62,1),
('히어로 63','heroes/hero_63.jpg','축복의 교회','Blessed Church','축복이 넘치는','Overflowing Blessings',63,1),
('히어로 64','heroes/hero_64.jpg','성결의 교회','Holy Church','성결한 삶','A Holy Life',64,1),
('히어로 65','heroes/hero_65.jpg','지혜의 교회','Wise Church','지혜롭게 행하는','Acting Wisely',65,1),
('히어로 66','heroes/hero_66.jpg','인내의 교회','Patient Church','인내로 이기는','Overcoming with Patience',66,1),
('히어로 67','heroes/hero_67.jpg','충성의 교회','Faithful Church','충성스럽게 섬기는','Serving Faithfully',67,1),
('히어로 68','heroes/hero_68.jpg','열정의 교회','Passionate Church','열정으로 불타는','Burning with Passion',68,1),
('히어로 69','heroes/hero_69.jpg','감동의 교회','Moving Church','감동을 주는','Touching Hearts',69,1),
('히어로 70','heroes/hero_70.jpg','영향력 교회','Influential Church','세상에 영향을 주는','Influencing World',70,1),
('히어로 71','heroes/hero_71.jpg','책임의 교회','Responsible Church','책임을 다하는','Taking Responsibility',71,1),
('히어로 72','heroes/hero_72.jpg','약속의 교회','Covenant Church','약속을 지키는','Keeping Promises',72,1),
('히어로 73','heroes/hero_73.jpg','은총의 교회','Church of Favor','은총을 입은','Favored by Grace',73,1),
('히어로 74','heroes/hero_74.jpg','찬송의 교회','Singing Church','찬송으로 예배하는','Worshiping with Hymns',74,1),
('히어로 75','heroes/hero_75.jpg','전파의 교회','Proclaiming Church','복음을 전파하는','Proclaiming Gospel',75,1),
('히어로 76','heroes/hero_76.jpg','갱신의 교회','Renewing Church','늘 새로워지는','Always Being Renewed',76,1),
('히어로 77','heroes/hero_77.jpg','돌봄의 교회','Caring Church','서로 돌보는','Caring for Each Other',77,1),
('히어로 78','heroes/hero_78.jpg','격려의 교회','Encouraging Church','서로 격려하는','Encouraging Each Other',78,1),
('히어로 79','heroes/hero_79.jpg','공의의 교회','Just Church','공의를 세우는','Establishing Justice',79,1),
('히어로 80','heroes/hero_80.jpg','긍휼의 교회','Merciful Church','긍휼을 베푸는','Showing Mercy',80,1),
('히어로 81','heroes/hero_81.jpg','지식의 교회','Knowledgeable Church','말씀을 배우는','Learning the Word',81,1),
('히어로 82','heroes/hero_82.jpg','이해의 교회','Understanding Church','서로 이해하는','Understanding Each Other',82,1),
('히어로 83','heroes/hero_83.jpg','통찰의 교회','Insightful Church','깊이 생각하는','Thinking Deeply',83,1),
('히어로 84','heroes/hero_84.jpg','연구의 교회','Studying Church','말씀을 연구하는','Studying the Word',84,1),
('히어로 85','heroes/hero_85.jpg','적용의 교회','Applying Church','말씀을 적용하는','Applying the Word',85,1),
('히어로 86','heroes/hero_86.jpg','실천의 교회','Practicing Church','믿음을 실천하는','Practicing Faith',86,1),
('히어로 87','heroes/hero_87.jpg','증거의 교회','Witnessing Church','삶으로 증거하는','Witnessing through Life',87,1),
('히어로 88','heroes/hero_88.jpg','고백의 교회','Confessing Church','신앙을 고백하는','Confessing Faith',88,1),
('히어로 89','heroes/hero_89.jpg','헌금의 교회','Generous Church','기쁨으로 드리는','Giving with Joy',89,1),
('히어로 90','heroes/hero_90.jpg','절제의 교회','Temperate Church','절제하는 삶','Life of Temperance',90,1),
('히어로 91','heroes/hero_91.jpg','정결의 교회','Pure Church','정결함을 지키는','Maintaining Purity',91,1),
('히어로 92','heroes/hero_92.jpg','인도의 교회','Guided Church','성령의 인도를 받는','Guided by Spirit',92,1),
('히어로 93','heroes/hero_93.jpg','보호의 교회','Protected Church','하나님의 보호 안에','Under God Protection',93,1),
('히어로 94','heroes/hero_94.jpg','공급의 교회','Provided Church','채움을 경험하는','Experiencing Provision',94,1),
('히어로 95','heroes/hero_95.jpg','동행의 교회','Walking Together','함께 걷는','Walking Together',95,1),
('히어로 96','heroes/hero_96.jpg','동역의 교회','Co-laboring Church','함께 일하는','Working Together',96,1),
('히어로 97','heroes/hero_97.jpg','동참의 교회','Participating Church','함께 참여하는','Participating Together',97,1),
('히어로 98','heroes/hero_98.jpg','완성의 교회','Complete Church','완성을 향해','Moving toward Completion',98,1),
('히어로 99','heroes/hero_99.jpg','영원의 교회','Eternal Church','영원을 소망하는','Hoping for Eternity',99,1),
('히어로 100','heroes/hero_100.jpg','새 하늘 새 땅','New Heaven New Earth','약속을 기다리는','Waiting for the Promise',100,1);
